#!/usr/bin/env python
# reuzblcat - safely push html to reuzbl
# See http://www.reuzbl.org/wiki/html-mode

from sys import stdin, stdout

stdout.write("uri data:text/html,")
for line in stdin:
    stdout.write(line[0:-1])

# vim: set noet ff=unix
